import './SimplePage.scss'

export default function SimplePage(): JSX.Element {

    return (
        <div className="simple-page">
            <h1>Welcome simple page</h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque dicta amette repudiandae dignissimos dolores voluptatum saepe rerum? Ipsum, deleniti sapiente numquam odio accusantium omnis amet culpa, dolorum eos hic non.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi repellat, similique reiciendis quod velit amet veniam minus est voluptates explicabo quisquam ex provident culpa ea ipsa neque eos error labore.</p>
        </div>
    );
}
